# Password Generator

# This program generates a random password consisting of letters, symbols and numbers.
# The number of characters for each of those categories is specified by the user.

# The program generates 2 passwords for the user to choose:
# Easy password: Generated by a sequence of random letters, symbols and numbers, in that order.
# Hard password: Generated by a random (shuffled) sequence of letters, symbols and numbers.

import random

letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
symbols = ['!', '#', '$', '%', '&', '(', ')', '^', '*', '+', '_']

print("Welcome to the PyPassword Generator!")
nr_letters = int(input("How many letters would you like in your password?\n"))
nr_symbols = int(input("How many symbols would you like in your password?\n"))
nr_numbers = int(input("How many numbers would you like in your password?\n"))

# Easy version (returns a password generated by letters, numbers, and symbols, in that order)
password = ""

for i in range(0, nr_letters):
    password += random.choice(letters)
for i in range(0, nr_numbers):
    password += random.choice(numbers)
for i in range(0, nr_symbols):
    password += random.choice(symbols)

print(f"Your easy password is: {password}")

# Hard version (returns a random sequence of all the characters)
password_elements = list(range(nr_letters + nr_numbers + nr_symbols))
for i in range(0, nr_letters):
    password_elements[i] = random.choice(letters)
    # I could have used password_elements.append(random.choice(letters))
for i in range(0, nr_numbers):
    password_elements[i + nr_letters - 1] = random.choice(numbers)
for i in range(0, nr_symbols):
    password_elements[i + nr_letters + nr_numbers - 1] = random.choice(symbols)

random.shuffle(password_elements)
#print(password_elements)

password_hard = ''
for i in range (0, nr_letters + nr_numbers + nr_symbols):
    password_hard += str(password_elements[i])
# OR
# for char in password_elements:
    # password_hard += char

print(f"Your hard password is: {password_hard}")